name: contact
favicon: null
layout_spectrum: 0.5852314203511924
typography_spectrum: 0.8072863721754402
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#ffffff'
    - '#0000ff'
    - '#77473a'
    - '#004dd3'
  brandStrength: 1
  lightness: 0.19699766440317035
  saturation: 0.7882305739913136
  rhythmicContrast: 0.25867606047540903
purpose: []
